version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: echo "Hello Everyone"
      - run:
          name: Curl a page
          command: curl https://www.google.com
      - run:
          name: Ping to remote IP
          command: ping 10.20.1.2
